spring:
  jackson:
    serialization:
      indent-output: true
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterAccess=1m

server:
  port: 8081
  servlet:
    context-path: /stock-moex-app-api
    encoding:
      charset: UTF-8
      force: true
  shutdown: graceful

stock:
  endpoint:
    adapterBase: /v1
    getCurrentPrice: /getCurrentPrice
    getLastDayPrice: /getLastDayPrice
    moexBase: https://iss.moex.com/iss
    moexCurrentPrice: /engines/stock/markets/shares/boards/TQBR/securities.json?iss.meta=off&iss.only=marketdata
    moexLastDayPrice: /engines/stock/markets/shares/boards/TQBR/securities.json?iss.meta=off&iss.only=securities

logging:
  level:
    #   root: INFO
    line.stockmoex: DEBUG
    javax:
      persistence:
        spi: ERROR
feign:
  autoconfiguration:
    jackson:
      enabled: true
  client:
    config:
      moex-client:
        connectTimeout: 2000
        readTimeout: 7000